# Generated by Django 4.0.6 on 2023-06-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_enddaydailyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enddaydailyreport',
            unique_together={('created_date', 'start_bill', 'end_bill')},
        ),
    ]
