# Generated by Django 4.0.6 on 2023-09-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_cashdrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrop',
            name='expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
