# Generated by Django 4.0.6 on 2023-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_cashdrop_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashdrop',
            old_name='balance',
            new_name='opening_balance',
        ),
        migrations.AddField(
            model_name='cashdrop',
            name='remaining_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
