# Generated by Django 4.0.6 on 2023-09-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_rename_balance_cashdrop_opening_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrop',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='cashdrop',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
