# Generated by Django 4.0.6 on 2023-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_cashdrop_branch_id_alter_cashdrop_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrop',
            name='datetime',
            field=models.CharField(max_length=200),
        ),
    ]
