# Generated by Django 4.0.6 on 2023-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_alter_table_options_branch_branch_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrop',
            name='is_end_day',
            field=models.BooleanField(default=True),
        ),
    ]
