# Generated by Django 4.0.6 on 2023-11-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_cashdrop_is_end_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrop',
            name='is_end_day',
            field=models.BooleanField(default=False),
        ),
    ]
