# Generated by Django 4.0.6 on 2024-04-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_cashdrop_latest_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
