# Generated by Django 4.0.6 on 2024-05-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_terminal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_layout',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.terminal'),
        ),
    ]
