# Generated by Django 4.0.6 on 2024-05-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_table_layout_terminal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_layout',
            old_name='height',
            new_name='desiredHeight',
        ),
        migrations.RenameField(
            model_name='table_layout',
            old_name='width',
            new_name='desiredWidth',
        ),
    ]
