# Generated by Django 4.0.6 on 2024-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_rename_height_table_layout_desiredheight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_estimate',
            field=models.BooleanField(default=False),
        ),
    ]
