# Generated by Django 4.0.6 on 2024-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_table_is_estimate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='is_estimate',
            new_name='is_estimated',
        ),
    ]
