# Generated by Django 4.0.6 on 2024-05-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_terminal_active_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='active_count',
        ),
    ]
