# Generated by Django 4.0.6 on 2024-05-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_devicetracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='is_active',
        ),
    ]
