# Generated by Django 4.0.6 on 2024-05-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_terminal_dayclose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailrecipient',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
