# Generated by Django 4.0.6 on 2024-06-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_printersetting_print_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='loyalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
