# Generated by Django 4.0.6 on 2024-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_organization_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='terminal_image',
            field=models.ImageField(blank=True, null=True, upload_to='terminal_images/'),
        ),
    ]
