# Generated by Django 4.0.6 on 2024-05-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_recipieitemsale_productrecipie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
