# Generated by Django 4.0.6 on 2024-05-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
