# Generated by Django 4.0.6 on 2024-09-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_menutype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipieitemsale',
            name='quantity',
        ),
    ]
