# Generated by Django 4.0.6 on 2024-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_recipieitemsale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipieitemsale',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
