# Generated by Django 4.0.6 on 2024-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_branchstocktracking_closing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstocktracking',
            name='closing',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchstocktracking',
            name='discrepancy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchstocktracking',
            name='opening',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchstocktracking',
            name='physical',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchstocktracking',
            name='received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchstocktracking',
            name='returned',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchstocktracking',
            name='sold',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchstocktracking',
            name='wastage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
