# Generated by Django 4.0.6 on 2024-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_itemreconcilationapiitem_physical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreconcilationapiitem',
            name='physical',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemreconcilationapiitem',
            name='returned',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemreconcilationapiitem',
            name='wastage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
