# Generated by Django 4.0.6 on 2024-10-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_average_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_prep_time',
        ),
    ]
