# Generated by Django 4.0.6 on 2024-10-01 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_average_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_prep_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
