# Generated by Django 4.0.6 on 2024-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_average_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecipie',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
