# Generated by Django 4.0.6 on 2024-10-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_tblmodifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='print_display',
            field=models.CharField(blank=True, choices=[('KITCHEN', 'KITCHEN'), ('BAR', 'BAR')], max_length=255, null=True),
        ),
    ]
