# Generated by Django 4.0.6 on 2023-08-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_enddaydailyreport_unique_together'),
        ('bill', '0005_tablreturnentry_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch'),
        ),
    ]
