# Generated by Django 4.0.6 on 2024-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_order_orderdetails_bill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='botID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
