# Generated by Django 4.0.6 on 2024-04-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_orderdetails_botid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='modification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
