# Generated by Django 4.0.6 on 2024-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_orderdetails_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_end_day',
            field=models.BooleanField(default=False),
        ),
    ]
