# Generated by Django 4.0.6 on 2024-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_bill_is_end_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terminal_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
