# Generated by Django 4.0.6 on 2024-05-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_voidbilltracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.order'),
        ),
    ]
