# Generated by Django 4.0.6 on 2024-05-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_alter_bill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='voidbilltracker',
            name='new_bill_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voidbilltracker',
            name='prev_bill_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
