# Generated by Django 4.0.6 on 2024-05-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_voidbilltracker_new_bill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voidbilltracker',
            name='bill_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_new_trackers', to='bill.bill'),
        ),
        migrations.AddField(
            model_name='voidbilltracker',
            name='bill_prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_prev_trackers', to='bill.bill'),
        ),
    ]
