# Generated by Django 4.0.6 on 2024-05-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_voidbilltracker_bill_new_voidbilltracker_bill_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitemvoid',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitemvoid',
            name='isBefore',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='billitemvoid',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.order'),
        ),
        migrations.AlterField(
            model_name='billitemvoid',
            name='bill_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.billitem'),
        ),
    ]
