# Generated by Django 4.0.6 on 2024-06-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_mobilepaymenttype_mobilepaymentsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepaymentsummary',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.mobilepaymenttype'),
        ),
    ]
