# Generated by Django 4.0.6 on 2024-06-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_loyalty_points'),
        ('organization', '0036_enddaydailyreport_delivery_grandtotal_and_more'),
        ('product', '0011_productpoints_customerproductpointstrack'),
        ('bill', '0021_mobilepaymentsummary_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('table_no', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_id', models.IntegerField(blank=True, null=True)),
                ('start_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('no_of_guest', models.IntegerField(blank=True, null=True)),
                ('employee', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_saved', models.BooleanField(blank=True, default=True, null=True)),
                ('terminal_no', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.terminal')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FutureOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_quantity', models.PositiveBigIntegerField(default=1)),
                ('kotID', models.CharField(blank=True, max_length=255, null=True)),
                ('botID', models.CharField(blank=True, max_length=255, null=True)),
                ('modification', models.CharField(blank=True, max_length=255, null=True)),
                ('ordertime', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.futureorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
