# Generated by Django 4.0.6 on 2024-07-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0024_futureorder_special_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureorder',
            name='bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.bill'),
        ),
    ]
