# Generated by Django 4.0.6 on 2024-07-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0025_futureorder_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureorder',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.order'),
        ),
    ]
