# Generated by Django 4.0.6 on 2024-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0027_futureorderdetails_rate_orderdetails_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
