# Generated by Django 4.0.6 on 2024-09-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_orderdetails_done_orderdetails_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='completed_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
