# Generated by Django 4.0.6 on 2024-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0032_tblordertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblordertracker',
            name='state',
            field=models.CharField(blank=True, default='Normal', max_length=100, null=True),
        ),
    ]
