# Generated by Django 4.0.6 on 2024-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0034_tblordertracker_prep_time_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblordertracker',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
