# Generated by Django 4.0.6 on 2024-10-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0035_tblordertracker_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblordertracker',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
