# Generated by Django 4.0.6 on 2024-10-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0036_tblordertracker_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futureorder',
            name='order',
        ),
    ]
