# Generated by Django 4.0.6 on 2024-10-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0037_remove_futureorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.order'),
        ),
    ]
