# Generated by Django 4.0.6 on 2024-10-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('bill', '0040_billitemvoid_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discountId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discount.discounttable'),
        ),
    ]
