# Generated by Django 4.0.6 on 2024-09-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userlogin_customer_cardno_customer_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='review_points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_points',
        ),
    ]
