# Generated by Django 4.0.6 on 2024-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customer_review_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
