# Generated by Django 4.0.6 on 2024-10-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_agentkitchenbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentkitchenbar',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
