# Generated by Django 4.0.6 on 2024-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_agentkitchenbar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentkitchenbar',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
