# Generated by Django 4.0.6 on 2024-10-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_agentkitchenbar_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentkitchenbar',
            name='branch',
        ),
    ]
