# Generated by Django 4.0.6 on 2024-10-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_terminal_terminal_image'),
        ('user', '0011_remove_agentkitchenbar_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentkitchenbar',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.branch'),
        ),
    ]
