# Generated by Django 4.0.6 on 2024-09-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='respro_itemId',
        ),
    ]
