# Generated by Django 4.0.6 on 2024-09-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_resproproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='resproproduct',
        ),
    ]
