# Generated by Django 4.0.6 on 2024-09-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_scanpayorder_code'),
        ('menu', '0007_menu_resproproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblredeemedproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.scanpayorder'),
        ),
    ]
