# Generated by Django 4.0.6 on 2024-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpayorder',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
